### ISSUE TITLE
Initial build of corner never finished for osx/python 3.5

### ISSUE THREAD

**Issue by mwcraig** [conda-forge/corner-feedstock#1]
I'd fix this immediately but this repo hasn't been updated yet with the new token (see conda-forge/conda-forge.github.io#426). When this repo has been fixed I can update the build.

**Comment by pkgw** [comment]
OK. As far as I can tell, we just have to wait for the repair script to construct a PR for this repo? It seems that we could expedite the process if needed. Based on the comments in the naima request it sounds as if this is not viewed as a very urgent problem, though.

**Comment by mwcraig** [comment]
Yeah, at first I thought it was a rush but then realized I could work around it with selectors. Given the size of the backlog this doesn't seem too urgent.

**Comment by synapticarbors** [comment]
This is causing issues for https://github.com/conda-forge/staged-recipes/pull/4531. Any progress on fixing this?

**Comment by pkgw** [comment]
I suspect not. I should understand how the system works better, but I don't — if I rerender and file a PR bumping the build number, will that iron things out?

**Comment by synapticarbors** [comment]
I'm not sure @jakirkham, @ocefpaf any ideas?

**Comment by pkgw** [comment]
Well, I filed #2 to get the machinery in motion.

**Comment by pkgw** [comment]
Ah, and the most recent commit on master shows that the repo had its token updated. So I believe that #2 will do the job.

**Comment by jakirkham** [comment]
Have just triggered a [job on Travis CI for `master`]( https://travis-ci.org/conda-forge/corner-feedstock/builds/314046852 ) in case that helps. FTR anyone can do this.

<img width="1552" alt="screen shot 2017-12-09 at 13 42 01" src="https://user-images.githubusercontent.com/3019665/33798472-c5de2f7a-dce6-11e7-8d35-77af9cd2b307.png">

Edit: Will need a custom message to override the `[ci skip]`.

**Comment by pkgw** [comment]
Thanks @jakirkham ! It looks like the OSX/3.5 package is now up on anaconda.org so hopefully conda-forge/staged-recipes#4531 can proceed.
